# Generated by Django 5.0.6 on 2025-03-18 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email',
        ),
        migrations.AlterField(
            model_name='profile',
            name='email_token',
            field=models.CharField(default='e8d73f8a-6236-4565-b9b3-7dc09118e5c5', max_length=100, unique=True),
        ),
    ]
