# Generated by Django 5.0.6 on 2025-04-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_profile_email_alter_profile_email_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_token',
            field=models.CharField(default='f31022f6-79c2-4a2f-a569-acfefe7a7d54', max_length=100, unique=True),
        ),
    ]
