# Generated by Django 5.0.6 on 2025-04-02 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_profile_email_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_token',
            field=models.CharField(default='d105d406-6046-443f-979f-8f02b5760663', max_length=100, unique=True),
        ),
    ]
