# Generated by Django 5.0.6 on 2025-04-07 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_email_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_token',
            field=models.CharField(default='7979d5ac-1f35-4ad5-bd51-c450fc42168f', max_length=100, unique=True),
        ),
    ]
