# Generated by Django 5.0.6 on 2025-04-12 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_email_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_token',
            field=models.CharField(default='6ae73757-c106-4e9f-a0ee-670ef229fc17', max_length=100, unique=True),
        ),
    ]
