# Generated by Django 5.0.6 on 2025-04-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_profile_email_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_token',
            field=models.CharField(default='f497151c-98b0-4f5e-bf9b-aa6cc08b62d1', max_length=100, unique=True),
        ),
    ]
