# Generated by Django 5.0.6 on 2025-04-13 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_profile_email_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_token',
            field=models.CharField(default='0301bca8-3af7-404e-a842-4b1ce653d63f', max_length=100, unique=True),
        ),
    ]
