# Generated by Django 5.0.6 on 2025-04-13 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_profile_email_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_token',
            field=models.CharField(default='fa3a71d1-11c4-451e-bb67-c0a11c3cb3d0', max_length=100, unique=True),
        ),
    ]
