# Generated by Django 5.0.6 on 2025-04-13 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_profile_email_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_token',
            field=models.CharField(default='0e6524b4-35ec-40c7-be96-0ede94a0218a', max_length=100, unique=True),
        ),
    ]
