# Generated by Django 5.0.6 on 2025-04-13 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_profile_email_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_token',
            field=models.CharField(default='ae2a9986-6c2c-497e-86eb-6a65df1392f7', max_length=100, unique=True),
        ),
    ]
