# Generated by Django 5.0.6 on 2025-04-13 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_profile_email_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_token',
            field=models.CharField(default='ea6c058f-fefd-457c-ada4-a556ee9b6ff9', max_length=100, unique=True),
        ),
    ]
