# Generated by Django 5.0.6 on 2025-04-13 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_alter_profile_email_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_token',
            field=models.CharField(default='aa0fb251-520c-45fb-b888-7eb7bd62b878', max_length=100, unique=True),
        ),
    ]
