# Generated by Django 5.0.6 on 2025-04-13 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_profile_email_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_token',
            field=models.CharField(default='d974dbdc-03ab-4035-8a62-274864640f1e', max_length=100, unique=True),
        ),
    ]
