# Generated by Django 5.0.6 on 2025-04-13 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_profile_email_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_token',
            field=models.CharField(default='c92ef82d-89a9-4c73-b9de-974c9cd9b0a1', max_length=100, unique=True),
        ),
    ]
