# Generated by Django 5.0.6 on 2025-04-13 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_alter_profile_email_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_token',
            field=models.CharField(default='5e7b18cc-276a-4b0b-85df-d81b31fd5379', max_length=100, unique=True),
        ),
    ]
