# Generated by Django 5.0.6 on 2025-04-13 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_alter_profile_email_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_token',
            field=models.CharField(default='b7b35997-4ba7-478b-8fb0-3300f3ac0a7a', max_length=100, unique=True),
        ),
    ]
