# Generated by Django 5.0.6 on 2025-04-13 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_alter_profile_email_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_token',
            field=models.CharField(default='029c7865-0bfd-461b-baee-8102acb9db01', max_length=100, unique=True),
        ),
    ]
