# Generated by Django 5.0.6 on 2025-04-13 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_alter_profile_email_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_token',
            field=models.CharField(default='7f03ccbb-24dd-42af-a0ff-e1f4aada2615', max_length=100, unique=True),
        ),
    ]
