# Generated by Django 5.0.6 on 2025-04-13 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_alter_profile_email_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_token',
            field=models.CharField(default='f8b7d89e-ccd5-4ba4-84a3-268f014a7246', max_length=100, unique=True),
        ),
    ]
