# Generated by Django 5.0.6 on 2025-04-13 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0026_alter_profile_email_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_token',
            field=models.CharField(default='ed1f96fe-4f2d-44a7-9736-aaafdf1e8a3e', max_length=100, unique=True),
        ),
    ]
