# Generated by Django 5.0.6 on 2025-04-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_profile_email_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_token',
            field=models.CharField(default='1de1819b-fb94-44e4-aad2-bc16473c2aa7', max_length=100, unique=True),
        ),
    ]
