# Generated by Django 5.0.6 on 2025-04-13 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_alter_profile_email_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='email_token',
            field=models.CharField(default='55c04112-e390-4698-be05-a980a251ecec', max_length=100, unique=True),
        ),
    ]
