# Generated by Django 5.0.6 on 2025-04-09 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_alter_stolenitem_user_message_notification_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportitem',
            name='location_description',
        ),
    ]
