# Generated by Django 5.0.6 on 2025-04-12 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_match'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='subject',
        ),
    ]
